### PR TITLE
[In Progress] Tree View

### PR DESCRIPTION
**Pull request by guidiego**
Hey Guys, I got tree view to play a little with the code, and start to be that dynamic :D I'm open this PR to track my commits and got discussions about the implementations :)

Let me know how can I help u :metal:

### CODE REVIEW

**Comment by guidiego** [comment]
Question: In json I use active to display an empty/full circle in tree, what the ideia for this circle be or not filled?

Question2: In a fild we have informations like: className, name, type and another stuff, you guys want to have this in EVERY component and open this with a onClick handle?

@JiniHendrix

**Comment by guidiego** [comment]
@znk I forgot to checkout the file! But this PR are in progress untill I understand the points that I comment before, so I will revert in next commit :D

**Comment by markmarcelo** [comment]
the components look good. perhaps you can split the request w/o the changes to package.json.

**Comment by guidiego** [comment]
@markmarcelo yeah! Like I said, I forgot to checkout package.json :)

This pr stay in progress, I need more information to finish that :) 
Would you know to answer me any of the questions that I left up there?

**Pull request closed without merging**
