### PR TITLE
Removed fs module from dependencies

### PR DESCRIPTION
**Pull request by levrik**
`fs` is a core node module and should not be installed via `npm`.

### CODE REVIEW

**Comment by prajapati-parth** [comment]
@levrik I do the same in one of my app. If you could please explain or give a reference why `fs` should not be installed via npm it would be great.
Thanks.

**Comment by levrik** [comment]
@prajapati-parth See https://www.npmjs.com/package/fs

**Comment by levrik** [comment]
@prajapati-parth Most of the fs module is native C++ code living inside Node.js itself (see https://github.com/nodejs/node/blob/096508dfa97c6b10ed16db1f20da0cbe6ef808b0/lib/fs.js#L33) and the actual package from NPM really does nothing (https://www.npmjs.com/package/fs)

**Comment by prajapati-parth** [comment]
@levrik Gotcha! Thank you.

**Pull request closed without merging**
